# Change these first
owner: noahc3 # Your GitHub organization or username, where this repository lives
repo: SDSetupStatus # The name of this repository

sites:
  - name: SDSetup Frontend
    url: https://www.sdsetup.com
  - name: SDSetup Backend
    url: https://files.sdsetup.com/api/v1/get/latestpackageset
  - name: Switch Homebrew Guide
    url: https://switch.homebrew.guide
  - name: PegaScape Landing
    url: https://pegascape.sdsetup.com
  - name: PegaScape Selector (Prompt)
    url: http://51.15.245.41
  - name: PegaScape DNS (Prompt)
    check: "tcp-ping"
    url: 51.15.245.41
    port: 53
  - name: PegaScape Selector (Applet)
    url: http://163.172.181.170
  - name: PegaScape DNS (Applet)
    check: "tcp-ping"
    url: 163.172.181.170
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statusbeta.sdsetup.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SDSetup Service Status
  introTitle: "SDSetup Service Status"
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/noahc3/SDSetup

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
